

def mock_gateway_service(params):
    """
    Mock gateway service that simulates a response based on the input parameters.
    """
    try:
        apiId = params.get("Head").get("ApiId")
    except Exception as e:
        return {
            "code": 500,
            "msg": "参数错误",
        }
    mock_data1 = {
        "Body": {
            "pubSysCode": "iops.odsm",
            "RetMsg": "查询成功",
            "TotalCount": 114,
            "RetCode": 200,
            "header": [
                "col1",
                "APPID",
                "totalBusTransCount",
                "tecSuccRate",
                "appAvgProcTime",
                "tecFailCount",
                "tecSuccCount",
                "maxProcTime",
                "minProcTime",
                "tps",
                "tm"
            ],
            "Result": [
                {
                    "tecSuccRate": 1.0,
                    "APPID": "CUTP_PP",
                    "totalBusTransCount": 1,
                    "appAvgProcTime": 42.0,
                    "minProcTime": 42,
                    "maxProcTime": 42,
                    "tps": 1,
                    "tecFailCount": 0,
                    "tm": "2025-08-06 08:43:00",
                    "tecSuccCount": 1,
                    "col1": 1
                },
                {
                    "tecSuccRate": 1.0,
                    "APPID": "CUTP_PP",
                    "totalBusTransCount": 1,
                    "appAvgProcTime": 4006.0,
                    "minProcTime": 4006,
                    "maxProcTime": 4006,
                    "tps": 1,
                    "tecFailCount": 0,
                    "tm": "2025-08-06 08:50:00",
                    "tecSuccCount": 1,
                    "col1": 1
                }
            ]
        },
        "Head": {
            "api_id": "ODSM_MulPASOTrans_004",
            "Token": "5f8deb2921a44288a2dd147848b544da",
            "CnsmrSvcNo": "10.240.41.10",
            "GlblSrlNo": "2023022213300000000000000001",
            "CnsmrTxnCd": "9801",
            "CnlTxnCd": "ODSM00001",
            "PvdrSrlNo": "Ignored_Trace",
            "SvcVerNo": "1.0",
            "content-type": "application/json",
            "PvdrSysId": "iops.odsm",
            "TxnDt": "20230222",
            "MAC": "4F5B78F245779A61",
            "SysRsrvFlgStr": "remark",
            "InttCnlCd": "C72",
            "RetCd": "200",
            "RetMsg": "网关层服务正常",
            "TxnTm": "212000",
            "InstId": "IAFDP",
            "MsgVerNo": "3.0",
            "UsrNo": "IAFDP",
            "OrgnlCnsmrSvcNo": "10.240.41.10",
            "SysRsrvStr": "remark",
            "CnsmrSysId": "IAFDP",
            "ApiId": "ODSM_MulPASOTrans_004",
            "OrgnlCnsmrSysId": "IAFDP",
            "CnsmrSrlNo": "20230724000001"
        }
    }
    mock_data2 = {
        "Body": {
        "pubSysCode": "iops.odsm",
        "RetMsg": "查询成功",
        "TotalCount": 174,
        "RetCode": 200,
        "header": [
            "UID",
            "APPID",
            "TIME",
            "STID",
            "TCUID",
            "IUID",
            "MODID",
            "MSID",
            "MSN",
            "TTID",
            "TTN",
            "TRIID",
            "T1",
            "T2",
            "T3",
            "T4",
            "TBS",
            "BEC",
            "BEM",
            "TTS",
            "TEC",
            "TEM",
            "TUCUID",
            "TSCAPPID",
            "TUCMSID",
            "TUCMSN",
            "TUCSCID",
            "TUCSCN",
            "TDCMODID",
            "TDSIP",
            "TDSP",
            "TDCMSID",
            "TDCMSN",
            "TDCSCID",
            "TDCSCN",
            "TDCRIID",
            "TPIP",
            "TPP",
            "REGION",
            "AZ",
            "LDC",
            "CZ",
            "CUMID",
            "DEID",
            "OPID",
            "PNUM",
            "APPN",
            "TUCAPPID",
            "TUCAPPN",
            "TDCAPPID",
            "TDCAPPN",
            "IP",
            "NN",
            "LW",
            "LFN",
            "TPT",
            "BODY",
            "DAID",
            "CAID",
            "HAID"
        ],
        "Result": [{
            "TDCMSN": None,
            "TPIP": "10.240.64.230",
            "LW": "/cutpapp/log/data/",
            "TDCRIID": None,
            "LFN": "/cutpapp/log/data/collectApp_G4.log",
            "OPID": None,
            "STID": 0,
            "MODID": None,
            "TRIID": "CHLB033",
            "CUMID": None,
            "TUCSCID": "CHLB033",
            "TDCAPPN": "银联交易清算",
            "TBS": "0",
            "IP": "10.240.64.230",
            "TUCAPPN": None,
            "TUCUID": "202508069604193001130",
            "TSCAPPID": "TIP",
            "REGION": None,
            "UID": "2025080601900003000000068769",
            "PNUM": None,
            "AZ": None,
            "TTID": "CHLB033",
            "NN": "szkf-cutppp01",
            "DEID": None,
            "DAID": None,
            "TUCMSID": None,
            "LDC": None,
            "TDCMODID": None,
            "TTN": "账户限额查询",
            "TTS": "1",
            "TDCSCID": None,
            "TPP": None,
            "TUCAPPID": "Others",
            "TPT": 39.0,
            "T1": "2025-08-06T13:28:18.468",
            "TCUID": None,
            "T2": None,
            "T3": None,
            "T4": "2025-08-06T13:28:18.507",
            "BEC": None,
            "TUCMSN": None,
            "APPID": "CUTP_PP",
            "IUID": "115046249286284083201",
            "MSID": None,
            "CAID": "622468000531736438",
            "MSN": None,
            "TIME": "2025-08-06T13:28:18",
            "TDSP": None,
            "BEM": None,
            "TDCAPPID": "Others",
            "TEC": "000000",
            "APPN": "银联交易清算",
            "TDSIP": None,
            "HAID": None,
            "CZ": None,
            "TUCSCN": None,
            "TEM": "交易成功",
            "TDCMSID": None,
            "TDCSCN": None
        }]
    },
        "Head": {
        "api_id": "ODSM_TransDetail_001",
        "Token": "5f8deb2921a44288a2dd147848b544da",
        "CnsmrSvcNo": "10.240.41.10",
        "GlblSrlNo": "2023022213300000000000000001",
        "CnsmrTxnCd": "9801",
        "CnlTxnCd": "ODSM00001",
        "PvdrSrlNo": "Ignored_Trace",
        "SvcVerNo": "1.0",
        "content-type": "application/json",
        "PvdrSysId": "iops.odsm",
        "TxnDt": "20230222",
        "MAC": "4F5B78F245779A61",
        "SysRsrvFlgStr": "remark",
        "InttCnlCd": "C72",
        "RetCd": "200",
        "RetMsg": "网关层服务正常",
        "TxnTm": "212000",
        "InstId": "IAFDP",
        "MsgVerNo": "3.0",
        "UsrNo": "IAFDP",
        "OrgnlCnsmrSvcNo": "10.240.41.10",
        "SysRsrvStr": "remark",
        "CnsmrSysId": "IAFDP",
        "ApiId": "ODSM_TransDetail_001",
        "OrgnlCnsmrSysId": "IAFDP",
        "CnsmrSrlNo": "20230724000001"
    }
    }
    if apiId == 'ODSM_MulPASOTrans_004':
        return mock_data1
    elif apiId == 'ODSM_TransDetail_001':
        return mock_data2
    return {
        "code": 500,
        "msg": "未找到对应的API"
    }

